config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root to: "pages#home"

  resources :feedbacks, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  validates :username, :email, presence: true
  validates :email, email: true
  validates :message, length: { maximum: 1200 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable

  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:full_name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user|
      user.permit(:full_name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :authenticate_user!

  def new
    @feedback = Feedback.new
    @feedback.username = current_user.full_name
    @feedback.email = current_user.email
  end

  def create
    @feedback = Feedback.new(feedback_params)

    if @feedback.save
      send_email_to_admin
      redirect_to new_feedback_url, notice: t(".success")
    else
      render :new
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:username, :email, :message)
  end

  def send_email_to_admin
    ApplicationMailer.with(feedback: @feedback).send_feedback.deliver_later
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    protected

    def update_resource(resource, params)
      resource.update(params)
    end

    def account_update_params
      params = devise_parameter_sanitizer.sanitize(:account_update)

      if passwords_blank?(params)
        params.except(:password, :password_confirmation)
      else
        params
      end
    end

    def passwords_blank?(params)
      params[:password].blank? && params[:password_confirmation].blank?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.slim
footer.row
  .columns
    p &copy; Flatstack #{Time.zone.today.year}

app/views/application/_messages.html.slim
- flash.each do |type, content|
  div(class="callout #{type}" data-closable)
    = content
    button.close-button(tabindex="0" aria-label="Dismiss alert" type="button" data-close)
      span aria-hidden="true" &times;

app/views/application/_navigation.html.slim
.title-bar data-hide-for="medium" data-responsive-toggle="navigation_menu"
  button.menu-icon data-toggle="" type="button"
  title-bar-title Menu

nav.top-bar#navigation_menu
  = render "navigation_main"
  = render "navigation_user"

app/views/application/_navigation_main.html.slim
.top-bar-left
  ul.menu
    li = link_to "Techdiary", root_path
    - if user_signed_in?
      = link_to "Home", root_path
      = link_to "Send feedback", new_feedback_path

app/views/application/_navigation_user.html.slim
ul.top-bar-right.menu.dropdown(data-dropdown-menu)
  - if user_signed_in?
    li
      a = current_user.full_name
      ul.menu
        li = link_to "Edit profile", edit_user_registration_path
        li = link_to "Sign out", destroy_user_session_path
  - else
    = link_to "Sign in", new_user_session_path
    = link_to "Sign up", new_user_registration_path

app/views/feedbacks/new.html.slim
.grid-container
  .grid-x.grid-padding-y: h3.cell = t(".new")

  .grid-x.grid-padding-x.grid-padding-y
    .cell.medium-5
      = simple_form_for @feedback do |f|
        .form-inputs
          = f.input :username, required: true, autofocus: true
          = f.input :email, required: true
          = f.input :message, as: :text, input_html: { rows: 5, maxlength: 1200 }

        .form-actions
          = f.button :submit, t(".submit")

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Techdiary"

    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_pack_tag "application", "data-turbolinks-track": "reload"
    = csrf_meta_tag

  body
    = render "navigation"
    = render "messages"

    main.container
      = yield

    = render "footer"

app/views/pages/home.html.slim
.grid-container
  .grid-x.grid-padding-y: h2.cell Home

app/views/users/shared/_links.html.slim
h6 Anything else?
ul.no-bullet
  - if controller_name != "sessions"
    li = link_to "Sign in", new_session_path(resource_name)

  - if devise_mapping.registerable? && controller_name != "registrations"
    li = link_to "Create a new account", new_registration_path(resource_name)

  - if devise_mapping.recoverable? && controller_name != "passwords"
    li = link_to "Forgot your password?", new_password_path(resource_name)

  - if devise_mapping.confirmable? && controller_name != "confirmations"
    li = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)

  - if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != "unlocks"
    li = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)

  - if devise_mapping.omniauthable?
    - resource_class.omniauth_providers.each do |provider|
      li = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)